Create DATABASE	 BMS;

use BMS;
show databases;
DROP database BMS;
-- CUSTOMER_PERSONAL_INFOR

CREATE TABLE CUSTOMER_PERSONAL_INFO(
CUSTOMER_ID VARCHAR(5),
CUSTOMER_NAME VARCHAR(30),
DATE_OF_BIRTH DATE,
GUARDIAN_NAME VARCHAR(30),
ADDRESS VARCHAR(50),
CONTACT_NO BIGINT(10),
MAIL_ID VARCHAR(30),
GENDER CHAR(1),
MARITAL_STATUS VARCHAR(10),
IDENTIFICATION_DOC_TYPE VARCHAR(20),
ID_DOC_NO VARCHAR(20),
CITIZENSHIP VARCHAR(20),
CONSTRAINT CUS_PERS_INFO_PK PRIMARY KEY(CUSTOMER_ID));

Show tables;

-- CUSTOMER_REFERENCE_INFO

CREATE TABLE CUSTOMER_REFERRENCE_INFO
(
CUSTOMER_ID VARCHAR(5),
CUSTOMER_NAME VARCHAR(30),
DATE_OF_BIRTH DATE,
GUARDIAN_NAME VARCHAR(30),
ADDRESS VARCHAR(50),
CONTACT_NO VARCHAR(30),
MAIL_ID VARCHAR(10),
GENDER CHAR(1),
MARITAL_STATUS VARCHAR(20),
IDENTIFICATION_DOC_TYPE VARCHAR(20),
ID_DOC_NO VARCHAR(20),
CITIZENSHIP VARCHAR(10),
CONSTRAINT CUS_PERS_INFO_PK PRIMARY KEY(CUSTOMER_ID));

Show tables;
-- CUSTOMER_REFERENCE_INFO

CREATE TABLE CUSTOMER_REFERENCE_INFO
(
	CUSTOMER_ID VARCHAR(50),
	REFERENCE_ACC_NAME VARCHAR(20),
	REFERENCE_ACC_NO VARCHAR(16),
	REFERENCE_ACC_ADDRESS VARCHAR(50),
	RELATION VARCHAR(25),
	CONSTRAINT CUST_REF_INFO_PK PRIMARY KEY(CUSTOMER_ID),
	CONSTRAINT CUST_REF_INFO_FK FOREIGN KEY(CUSTOMER_ID) REFERENCES  CUSTOMER_PERSONAL_INFO(CUSTOMER_ID));

	show tables;
	
	-- BANK INFO

CREATE TABLE BANK_INFO(
	IFSC_CODE VARCHAR(15),
	BANK_NAME VARCHAR(25),
	BRANCH_NAME VARCHAR(25),
	CONSTRAINT BANK_INFO_PK PRIMARY KEY(IFSC_CODE));
	
	-- ACCOUNT_INFO

	CREATE TABLE ACCOUNT_INFO
	(
	ACCOUNT_NO BIGINT(16),
	CUSTOMER_ID VARCHAR(5),
	ACCOUNT_TYPE VARCHAR(10),
	REGISTRACTION_DATE DATE,
	ACTIVATION_DATE DATE,
	IFSC_CODE VARCHAR(10),
	INTEREST DECIMAL(7,2),
	INITIAL_DEPOSIT BIGINT(10),
	CONSTRAINT ACC_INFO_PK PRIMARY KEY(ACCOUNT_NO),
	CONSTRAINT ACC_INFO_PERS_FK FOREIGN	KEY(CUSTOMER_ID) REFERENCES 	CUSTOMER_PERSONAL_INFO (CUSTOMER_ID),
	CONSTRAINT ACC_INFO_BANK_FK FOREIGN KEY(IFSC_CODE) REFERENCES BANK_INFO 	(IFSC_CODE));

	show tables;

INSERT INTO  BANK_INFO(IFSC_CODE,BANK_NAME,BRANCH_NAME) VALUES('HDFC000035',                   'HDFC BANK', 'CST BRANCH');
INSERT INTO BANK_INFO(IFSC_CODE,BANK_NAME,BRANCH_NAME) VALUES('SBIN0070001','SBI BANK','MUMBAI MAIN BRANCH');
INSERT INTO BANK_INFO(IFSC_CODE,BANK_NAME,BRANCH_NAME) VALUES('BKID000001','BANK OF INDIA','MUMBAI BRANCH');
INSERT INTO BANK_INFO(IFSC_CODE,BANK_NAME,BRANCH_NAME) VALUES('ICIC0006239','ICICI BANK','MUMBAI-CHEMBUR BRANCH');

select * from bank_info;

-- CUSTOMER PERSONAL_INFO

INSERT INTO CUSTOMER_PERSONAL_INFO(CUSTOMER_ID,CUSTOMER_NAME,DATE_OF_BIRTH,GUARDIAN_NAME, ADDRESS, CONTACT_NO, MAIL_ID) VALUES('A0001','SURESH S','1989-12-24','SRINIVASAN','RN 714 MANKHURD MUMBAI','9082626959','sureshsrinivasan169@gmail.com');

INSERT INTO CUSTOMER_PERSONAL_INFO(CUSTOMER_ID,CUSTOMER_NAME,DATE_OF_BIRTH,GUARDIAN_NAME, ADDRESS, CONTACT_NO, MAIL_ID) VALUES('A0002','RAMESH S','1991-11-12','LAKSHMI','RN 400 GOVANDI','9820885439','ra123@gmail.com');

INSERT INTO CUSTOMER_PERSONAL_INFO(CUSTOMER_ID,CUSTOMER_NAME,DATE_OF_BIRTH,GUARDIAN_NAME, ADDRESS, CONTACT_NO, MAIL_ID) VALUES ('A0003','ANAND','2000-05_14','SRINIVASAN', 'RN 505 CHEMBUR','9999999990','vss12@gmail.com');

INSERT INTO CUSTOMER_PERSONAL_INFO(CUSTOMER_ID,CUSTOMER_NAME,DATE_OF_BIRTH,GUARDIAN_NAME, ADDRESS, CONTACT_NO ,MAIL_ID) VALUES ('A0005','SHRIYA V','2011-5-12','SONU','VASHI NAVIMUMBAI','8888888888','vss12@gmail.com');

INSERT INTO CUSTOMER_PERSONAL_INFO(CUSTOMER_ID,CUSTOMER_NAME,DATE_OF_BIRTH,GUARDIAN_NAME, ADDRESS, CONTACT_NO, MAIL_ID)VALUES ('A0006','SHRIHARSH','2000-06-30','VENKATESH','SANPADA NAVIMUMBAI','9820885454','vss12@gmail.com');
 
select *from CUSTOMER_PERSONAL_INFO;
 

